version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      azalea:
        patterns:
          - "azalea-*"
      vulkan:
        patterns:
          - "ash"
          - "ash-window"
          - "gpu-allocator"
      tauri:
        patterns:
          - "tauri"
          - "tauri-*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      react:
        patterns:
          - "react"
          - "react-*"
          - "@types/react*"
