// This file has been generated by Tauri Specta. Do not edit this file manually.
export type ConsoleMessageEvent = { type: "message"; val: string } | { type: "reset" };

export type GameExitedEvent = {
	code: number | null,
	signal: number | null,
	last_lines: string[] | null,
};

export type GameVersion = {
	id: string,
	version_type: string,
};

export type PatchNote = {
	title: string,
	version: string,
	date: string,
	summary: string,
	image_url: string,
	entry_type: string,
	content_path: string,
};
