// This file has been generated by Tauri Specta. Do not edit this file manually.
export type SavedServer = {
	name: string,
	address: string,
	category?: string,
};

export type ServerStatus = {
	online: boolean,
	players: number,
	max_players: number,
	ping_ms: number,
	motd: string,
	version: string,
};
