// This file has been generated by Tauri Specta. Do not edit this file manually.
export type Directory = string;

export type Id = string;

export type Installation = {
	id: Id,
	name: Name,
	version: Version,
	last_played: number | null,
	created_at: TimeStamp,
	directory: Directory,
	width: number,
	height: number,
	is_latest: boolean,
};

export type InstallationDraft = {
	name: string,
	version: string,
	directory: string,
	width: number,
	height: number,
};

export type InstallationError = { kind: "InvalidName" } | { kind: "NameTooLong"; detail: number } | { kind: "InvalidPath" } | { kind: "InvalidCharacter"; detail: string } | { kind: "ReservedName"; detail: string } | { kind: "DirectoryAlreadyExists" } | { kind: "InstallNotFound"; detail: Id } | { kind: "Io"; detail: string } | { kind: "Json"; detail: string } | { kind: "Other"; detail: string };

export type Name = string;

export type TimeStamp = number;

export type Version = string;
